version: '3.7'
services:
  soap-mysql:
    image: mysql:5.7
    ports:
      - "3311:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    env_file:
      - .env-db
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://0.0.0.0:3306" ]
      interval: 10s
      timeout: 120s
      retries: 11
  soap:
    depends_on:
      soap-mysql:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    env_file: .env
    ports:
      - '8091:8091'
    stdin_open: true
    tty: true
  soap-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8085:80'
    restart: always
    environment:
      PMA_HOST: soap-mysql
      UPLOAD_IMAGE: 300M
    depends_on:
      - soap-mysql

volumes:
  mysql-data: